import assert from "node:assert/strict";
import { buildAgentSystemPrompt, buildPlannerPrompt } from "../src/agent/prompts.js";
import { toolDefinitions } from "../src/agent/tools.js";

const system = buildAgentSystemPrompt({ systemAddendum: "Custom system prompt marker." });
assert.match(system, /Proof evidence policy/);
assert.match(system, /Custom system prompt marker/);
assert.match(system, /formula_transform/);
assert.match(system, /deterministically applies supplied formula transformations/);
assert.match(system, /action=plan_apply/);
assert.match(system, /do not call it again merely to restate the same transformation/);
assert.doesNotMatch(system, /integration-by-parts|product-rule transforms/i);
assert.match(system, /Do not use Wolfram tools to read local files/);
assert.match(system, /verification ledger/);
assert.match(system, /Avoid underscores in Wolfram symbol names/);
assert.match(system, /one to five explicit expressions/);
assert.match(system, /combine them as a Wolfram list/);
assert.match(system, /local estimate pattern hints recommend a compact ledger/);
assert.match(system, /first_tool_hint/);
assert.match(system, /sequential decomposition override/);
assert.match(system, /stable ledger expression/);
assert.match(system, /Do not invent representative formulas/);
assert.match(system, /original and rescaled variables/);
assert.match(system, /\(D\[expr, r\] \/. r -> 1\)/);
assert.match(system, /repeated derivatives inside list entries/);
assert.match(system, /do not use SameQ\/===/);
assert.match(system, /hypotheses in the tool assumptions field/);
assert.match(system, /prefer wolfram_equivalence_check over solving the original equation/);
assert.match(system, /Do not call wolfram_solve with variables=\{\}/);
assert.match(system, /dimensionless substitution d = a\*q/);
assert.match(system, /do not spend more tool calls retrying the same bare power inequality/);
assert.match(system, /positive-factor bound checks/);
assert.match(system, /do not spend follow-up calls on confirmatory Reduce/);
assert.match(system, /small-radius coercivity checks/);
assert.match(system, /rational positive-denominator comparisons/);
assert.match(system, /mutually exclusive case splits/);

const planner = buildPlannerPrompt("Base planner prompt.", { plannerAddendum: "Custom planner prompt marker." });
assert.match(planner, /Base planner prompt/);
assert.match(planner, /Planner-specific policy/);
assert.match(planner, /Custom planner prompt marker/);
console.log("prompt tests passed");