import type { ToolDefinition } from "../names.js";
import { defineTool } from "./define-tool.js";

export const proofToolDefinitions: ToolDefinition[] = [
  defineTool(
  "formula_transform",
  "Deterministically transform a supplied mathematical formula using the Wolfram FormulaTransformEngine. Use this when the user wants a concrete formula rewrite, inequality estimate, integration-by-parts step, Holder/Cauchy-Schwarz/Young transformation, Sobolev/Poincare estimate seed, structural derivative/product/commutator/normalization equality, direction-specific upper/lower/two-sided bound, or assumptions-aware side-condition ledger. It returns a complete relation, trace, discharged/deferred conditions, obligations, and round-trippable state. Prefer this over proof_pattern_engine for actual formula transformations.",
  {
    action: { type: "string", enum: ["apply", "plan_parts", "plan_apply", "compile_rule", "compile_heuristic", "compile_seed", "compile_planner", "compile_structural", "compile_discharger", "inspect_registry", "reload_registry", "get_obligations", "discharge_obligation"], description: "Formula-transform action. Use apply for ordinary transformations, plan_parts to ask Wolfram for target-guided candidate part paths and per-candidate previews, plan_apply to ask Wolfram for a one-shot target-guided part/parameter plan without mutating the registry, inspect_registry to list compiled JSON rules, reload_registry after persisted registry JSON changes, compile_rule/compile_heuristic/compile_seed/compile_planner/compile_structural/compile_discharger only when explicitly extending the engine, get_obligations to inspect deferred conditions, and discharge_obligation to consume obligations using assumptions/context and registered dischargers." },
    formula: { type: "string", description: "Formula in Wolfram InputForm syntax, preferably using Inactive heads such as Inactive[Integrate][f[x] g[x], {x,a,b}]. Empty is allowed for inspect_registry, reload_registry, and compile actions." },
    rule: { type: "string", description: "Transform rule, estimate seed, or structural transform name such as Holder, CauchySchwarz, Young, IntegrationByParts, Poincare, Sobolev, DerivativeProduct, CommutatorDerivative, NormalizeByFactor, or DropBoundaryTerm. Empty is allowed for inspect_registry, reload_registry, obligation actions, and plan_parts when only candidate part paths are needed." },
    direction: { type: "string", enum: ["Upper", "Lower", "TwoSided", "Equal", "Auto"], description: "Requested orientation. Upper returns selected <= bound, Lower returns lowerBound <= selected, TwoSided returns a chain, Equal is for equality transforms, Auto chooses the safest canonical relation such as Abs[selected] <= bound." },
    part: { type: "string", description: "Target part selector. Use Whole for the full formula, Auto with parameters.targetRelation or parameters.targetPattern to let Wolfram select the unique matching subexpression, Named:name with parameters.namedParts for a stable named subexpression selector, or an explicit Wolfram part path such as 1, 1,2, or {1,2} when the subexpression is known. targetRelation selects by its lhs; targetPattern is a one-shot Wolfram pattern such as a_ b_. If the part is uncertain or the target is embedded, use action=plan_parts to get candidate paths before apply/plan_apply." },
    parameters: { type: "string", description: "Rule parameters as JSON, e.g. {\"p\":2,\"q\":2}. For one-shot target adaptation, include targetRelation plus optional objective, absorbFactor, weight, allowedHeuristics, maxSearchDepth, and namedParts such as {\"nonlinear\":\"1\"} for part=Named:nonlinear. Use targetPattern only to select an embedded part by pattern, not as a persistent rule. Do not compile temporary targets into registry JSON. For weighted Holder, either pass weight as a Wolfram expression string or provide targetRelation with explicit weighted Lp/Lq norm factors so Wolfram can infer a consistent temporary weight. For DropBoundaryTerm, pass boundaryTerm as a Wolfram expression string. For discharge_obligation, pass {\"obligationId\":\"...\"} or leave empty to attempt all obligations." },
    assumptions: { type: "string", description: "Wolfram assumptions used to discharge generated transform conditions, e.g. p > 1 && q > 1 && 1/p + 1/q == 1. Conditions not discharged by assumptions/context are returned as obligations." },
    context: { type: "string", description: "Optional JSON or plain text analytic context such as domain, boundary data, function spaces, regularity, measurability/integrability, compact support, normalization, or real-valued declarations. Registered obligation dischargers match this context through restricted structured evidence rules and record the matched evidence in state." },
    state: { type: "string", description: "Prior FormulaTransformState in Wolfram InputForm syntax, or empty to start a new explicit round-trip ledger." },
    payload: { type: "string", description: "Rule, heuristic, estimate-seed, target-planner, structural-transform, or obligation-discharger JSON payload for compile_rule/compile_heuristic/compile_seed/compile_planner/compile_structural/compile_discharger. Do not include arbitrary Wolfram code; the Wolfram compiler accepts only the restricted JSON DSL." }
  }
),
  defineTool(
  "proof_pattern_engine",
  "Legacy/internal proof-pattern helper for abstract proof-state suggestions and compatibility. Do not use this for concrete formula transformations; use formula_transform instead. Use this only when the next step is to inspect old proof-pattern states, compatibility aliases, parameter choices, or legacy proof-move ledgers. It is not a whole-paper verifier and does not replace explicit Wolfram checks of resulting formulas.",
  {
    operation: { type: "string", enum: ["normalize", "suggest", "apply", "trace", "registry", "parameter", "compile", "register"], description: "Requested proof-transform action: prepare a state, ask for candidate moves, apply a move, inspect a trace, inspect available move families, choose a parameter condition, compile a supplied proof move into a ledger, or register a reusable transform only when explicitly asked to persist one." },
    goal: { type: "string", description: "Current formula, estimate, or proof target in Wolfram InputForm syntax; empty when state already contains the target." },
    known: { type: "string", description: "Known formulas, hypotheses, or previously verified consequences in Wolfram InputForm syntax, usually a list, or empty." },
    context: { type: "string", description: "Proof context in Wolfram InputForm syntax, preferably an Association describing domain, assumptions, admissible transformations, boundary data, parameters, and side conditions." },
    state: { type: "string", description: "Existing proof-state Association in Wolfram InputForm syntax, or empty to create one from goal/context/known." },
    moveId: { type: "string", description: "Candidate move identifier returned by suggest, or empty to apply the first suitable candidate." },
    ruleName: { type: "string", description: "Optional abstract transform family name for focused operations, or empty." },
    payload: { type: "string", description: "Auxiliary proof-transform data as a Wolfram Association in InputForm using <|key -> value|> syntax. Do not use JSON, XML-like wrappers, or <Association[...]> syntax. For compile, provide only intent-level fields such as RuleIntent, TransformIntents, ConditionIntents, and MissingConditionIntents. Do not include concrete formulas, parameter values, private example structure, or problem-specific side-condition text in the compile schema." }
  }
)
];
